routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('tasks', 'TasksController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
}

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'name',
        'priority',
        'project_id',
    ];

    public function project()
    {
        return $this->belongsTo(Project::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TaskStoreRequest;
use App\Project;
use App\Task;
use Illuminate\Http\Request;

class TasksController extends Controller
{
    /**
     * Display the list of Tasks
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $tasks = Task::orderBy('priority');

        if ($request->project){
            $tasks= $tasks->where('project_id', $request->project);
        }

        $tasks= $tasks->paginate(15);

        $projects = Project::all();
        return view('tasks.index', compact('tasks', 'projects'));
    }

    /**
     * Display the form to create new Task with the projects list
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $projects = Project::all();

        return view('tasks.create', compact('projects'));
    }

    /**
     * Store submitted Task after validating the form data
     *
     * @param TaskStoreRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(TaskStoreRequest $request)
    {
        $task             = new Task;
        $task->name       = $request->name;
        $task->priority   = $request->priority;
        $task->project_id = $request->project_id;

        if ($task->save()) {
            return back();
        }
    }

    /**
     * Display the page to edit the task
     * @param $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $task     = Task::with('project')->where('id', $id)->first();
        $projects = Project::all();

        return view('tasks.edit', compact('projects', 'task'));
    }

    /**
     * Update the task
     *
     * @param TaskStoreRequest $request
     * @param Task $task
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(TaskStoreRequest $request, Task $task)
    {
        $taskData = [
            'name'       => $request->name,
            'project_id' => $request->project_id,
            'priority'   => $request->priority,
        ];

        $task->update($taskData);

        return redirect()->route('tasks.index');

    }

    /**
     * Destroy the task and go back to tasks list
     *
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        Task::find($id)->delete();

        return back();
    }

    /**
     * Re-order tasks
     * @todo: enqueue this operation if the list of tasks  is big
     *
     * @param Request $request
     *
     * @return array
     */
    public function reOrder(Request $request)
    {
        foreach ($request->tasks as $priority => $id) {
            Task::find($id)->update(['priority' => $priority + 1]);
        }

        return response()->json([
            'data' => [
                'status' => 'successfully reordered the tasks',
            ],
        ], 200);
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>

<!-- Scripts -->
<script src="http://rubaxa.github.io/Sortable/Sortable.js"></script>
<script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/partials/nav.blade.php
<nav class="nav flex-column">
    <a class="nav-link" href="{{ route('tasks.index') }}">Tasks list</a>
    <a class="nav-link" href="{{ route('tasks.create') }}">Add new task</a>
</nav>

resources/views/tasks/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="card" >
                    <div class="card-body">
                      @include('partials.nav')
                    </div>
                </div>

            </div>
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form action="{{route('tasks.store')}}" method="post">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="project"> Select a project (optional) </label>
                                <select name="project_id" id="project" class="form-control">
                                    <option value="">No Project</option>
                                    @foreach($projects as $project)
                                        <option value="{{$project->id}}"> {{ $project->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="task">Task</label>
                                <input type="text" class="form-control" id="task" name="name" placeholder="Enter Task">
                            </div>

                            <div class="form-group">
                                <label for="priority">Priority</label>
                                <input type="number" class="form-control" id="priority" value="1" name="priority">
                            </div>

                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection()

resources/views/tasks/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        @include('partials.nav')
                    </div>
                </div>

            </div>
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form action="{{route('tasks.update', $task->id)}}" method="post">
                            {{ method_field('PATCH') }}

                            {{ csrf_field() }}

                            <input type="hidden" name="id" value="{{ $task->id }}">
                            <div class="form-group">
                                <label for="project"> Select a project (optional) </label>
                                <select name="project_id" id="project" class="form-control">
                                    <option value="">No Project</option>
                                    @foreach($projects as $project)
                                        <option
                                                value="{{$project->id}}"
                                                @if($project->id == $task->project_id) selected="selected" @endif >
                                            {{ $project->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="task">Task</label>
                                <input type="text"
                                       class="form-control"
                                       id="task"
                                       name="name"
                                       placeholder="Enter Task"
                                       value="{{ $task->name }}">
                            </div>

                            <div class="form-group">
                                <label for="priority">Priority</label>
                                <input type="number"
                                       class="form-control"
                                       id="priority"
                                       value="{{ $task->priority }}"
                                       name="priority">
                            </div>

                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection()

resources/views/tasks/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-3 p-1">
                <div class="card">
                    <div class="card-body">
                        @include('partials.nav')
                        <hr>
                        <h5>Filter by project</h5>
                        <form method="get" id="filter-form">
                            <select name="project" class="form-control">
                                @foreach($projects as $project)
                                    <option value="{{$project->id}}" >{{ $project->name }}</option>
                                @endforeach
                            </select>
                        </form>

                    </div>
                </div>

            </div>
            <div class="col-sm-9 p-1">
                <div class="card">
                    <div class="card-body">
                        @if(!$tasks)
                            There is no task yet, maybe it's time to
                            <a href="{{ route('tasks.create') }}">add new task</a>

                        @else
                            <div class="list-group" id="tasks" disabled>
                                @foreach($tasks as $task)
                                    <div class="list-group-item" data-id="{{ $task->id }}">

                                        <h3>{{ $task->name }}
                                            <small class="text-muted pl-1">priority: {{ $task->priority }} </small>
                                        </h3>

                                        <div class="ml-auto">

                                            <a class="btn btn-sm btn-outline-dark ml-2 float-right"
                                               href="{{ route('tasks.edit', $task->id ) }}"> edit </a>

                                            <form action="{{ route('tasks.destroy', $task->id) }}" method="post"
                                                  onsubmit="return confirm('Are you sure about that ?')"
                                                  class="float-right">

                                                {{ method_field('delete') }}
                                                {{ csrf_field() }}
                                                <button class="btn btn-sm btn-outline-danger" type="submit">delete
                                                </button>

                                            </form>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection()